// The checklist theme.
// Lengths use points (72 pt = 1 inch); content never controls typography.
#let theme = (
  font: "Helvetica Neue",
  header-font: "Helvetica",
  body-size: 8pt,
  body-weight: 500,
  footer-size: 10pt,
  note-size: 7pt,
  qualifier-size: 6pt,
  header-size: 9pt,
  header-height: 14pt,
  header-tracking: 0.7pt,
  row-gap: 2pt,
  line-leading: 3pt,
  note-leading: 2pt,
  response-gap: 3pt,
  branch-gap: 6pt,
  heading-gap: 2pt,
  note-gap: 2.5pt,
  section-gap: 6pt,
  inset: 3.5pt,
  box-margin: 3pt,
  condition-margin: 3pt,
  leader-gap: 1.25pt,
  leader-min: 5pt,
  normal-fill: rgb("e9e9e9"),
  emergency-fill: rgb("ff4949"),
  rule: 0.5pt,
  outline: 1pt,
)
